# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout-another-repo:
    runs-on: ubuntu-latest

    steps:
    # Step 1: checkout_private_repo
    - name: Checkout another repository
      uses: actions/checkout@v4
      with:
        repository: Jettpacked/Spotify_Stuff
        token: ${{ secrets.MY_PAT }}
        path: spotify_private_repo

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    # Step 3: Install Dependencies (if needed)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
